import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'fs-extra';
import path from 'path';

export const config = {
  maxDuration: 300
};

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST');
  
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { prompt, apiKey } = req.body;
  
  if (!apiKey || !prompt) {
    return res.status(400).json({ error: 'API key and prompt required' });
  }

  const projectId = `wfseek-${Date.now()}`;
  const projectPath = path.join('/tmp', projectId);

  try {
    // Generate code with Gemini
    const gemini = new GoogleGenerativeAI(apiKey);
    const model = gemini.getGenerativeModel({ 
      model: 'gemini-1.5-pro-latest',
      generationConfig: { temperature: 0.2, maxOutputTokens: 8192 }
    });

    const result = await model.generateContent(`
Create a Next.js 14 website for: "${prompt}"

Generate these files:
1. package.json - Next.js 14 with React, TypeScript, Tailwind
2. app/layout.tsx - Root layout
3. app/page.tsx - Main page with hero, features, about sections
4. app/globals.css - Tailwind + custom styles
5. tailwind.config.ts - Tailwind config
6. tsconfig.json - TypeScript config
7. postcss.config.js - PostCSS config
8. next.config.js - Next.js config with export

Make it modern, responsive, beautiful with animations.

Return ONLY in this exact format:
File: package.json
\`\`\`json
{ "name": "site", ... }
\`\`\`

File: app/page.tsx
\`\`\`tsx
// code
\`\`\`
`);

    const text = result.response.text();
    
    // Parse files
    const files = [];
    const regex = /File:\s*([^\n]+)\n```(?:\w+)?\n([\s\S]*?)```/g;
    let match;
    while ((match = regex.exec(text)) !== null) {
      files.push({ path: match[1].trim(), content: match[2].trim() });
    }

    if (files.length === 0) {
      throw new Error('No files generated by AI');
    }

    // Write files
    await fs.ensureDir(projectPath);
    for (const file of files) {
      const fullPath = path.join(projectPath, file.path);
      await fs.ensureDir(path.dirname(fullPath));
      await fs.writeFile(fullPath, file.content);
    }

    // Return success with file contents
    const fileContents = {};
    for (const file of files) {
      fileContents[file.path] = file.content;
    }

    return res.status(200).json({
      success: true,
      message: 'Website generated successfully!',
      files: fileContents,
      projectId
    });

  } catch (error) {
    console.error('Error:', error);
    
    // Cleanup
    try { await fs.remove(projectPath); } catch(e) {}
    
    return res.status(500).json({ 
      success: false,
      error: error.message || 'Build failed. Check your API key.'
    });
  }
}
