import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'fs-extra';
import path from 'path';

export const config = {
  maxDuration: 300
};

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { prompt, apiKey } = req.body;
  
  if (!apiKey || !prompt) {
    return res.status(400).json({ error: 'API key and prompt required' });
  }

  const projectId = `wfseek-${Date.now()}`;
  const projectPath = path.join('/tmp', projectId);

  try {
    console.log('🚀 Wfseek: Starting generation...');
    
    const gemini = new GoogleGenerativeAI(apiKey);
    const model = gemini.getGenerativeModel({ 
      model: 'gemini-1.5-pro-latest',
      generationConfig: { temperature: 0.2, maxOutputTokens: 8192 }
    });

    const result = await model.generateContent(`
Create a complete Next.js 14 website for: "${prompt}"

Generate these 8 files with complete code:

File: package.json
\`\`\`json
{
  "name": "wfseek-site",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.3.0",
    "postcss": "^8.4.0",
    "autoprefixer": "^10.4.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "typescript": "^5.3.0"
  }
}
\`\`\`

File: app/layout.tsx
\`\`\`tsx
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${prompt.substring(0, 30)}',
  description: 'Generated by Wfseek',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
\`\`\`

File: app/page.tsx
\`\`\`tsx
export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-900 to-black text-white">
      <div className="container mx-auto px-4 py-20">
        <h1 className="text-5xl font-bold mb-6">${prompt}</h1>
        <p className="text-xl text-gray-300">Generated by Wfseek AI</p>
      </div>
    </main>
  );
}
\`\`\`

File: app/globals.css
\`\`\`css
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  padding: 0;
}
\`\`\`

File: tailwind.config.ts
\`\`\`typescript
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
\`\`\`

File: tsconfig.json
\`\`\`json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
\`\`\`

File: postcss.config.js
\`\`\`javascript
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
\`\`\`

File: next.config.js
\`\`\`javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;
\`\`\`
`);

    const text = result.response.text();
    
    // Parse files
    const files = {};
    const regex = /File:\s*([^\n]+)\n```(?:\w+)?\n([\s\S]*?)```/g;
    let match;
    
    while ((match = regex.exec(text)) !== null) {
      files[match[1].trim()] = match[2].trim();
    }

    if (Object.keys(files).length === 0) {
      throw new Error('AI did not generate any files. Try again.');
    }

    console.log('✅ Generated files:', Object.keys(files));

    // Cleanup temp dir if exists
    try { await fs.remove(projectPath); } catch(e) {}

    return res.status(200).json({
      success: true,
      message: 'Website generated successfully!',
      files: files,
      projectId
    });

  } catch (error) {
    console.error('❌ Error:', error);
    
    try { await fs.remove(projectPath); } catch(e) {}
    
    return res.status(500).json({ 
      success: false,
      error: error.message || 'Generation failed. Check your API key.'
    });
  }
}
