import { GoogleGenerativeAI } from '@google/generative-ai';
import { execSync } from 'child_process';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { createWriteStream } from 'fs';
import archiver from 'archiver';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const config = {
  maxDuration: 300 // 5 minutes max
};

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { prompt, apiKey } = req.body;
  
  if (!apiKey || !prompt) {
    return res.status(400).json({ error: 'API key and prompt required' });
  }

  const projectId = `wfseek-${Date.now()}`;
  const projectPath = path.join('/tmp', projectId);
  const deployToken = process.env.VERCEL_TOKEN;

  try {
    console.log('🚀 Wfseek: Starting build...');
    
    // 1. Initialize Gemini
    const gemini = new GoogleGenerativeAI(apiKey);
    const model = gemini.getGenerativeModel({ 
      model: 'gemini-1.5-pro-latest',
      generationConfig: { 
        temperature: 0.2, 
        maxOutputTokens: 8192 
      }
    });

    // 2. Generate website code
    console.log('🤖 Wfseek: Generating code...');
    const generationPrompt = `
Create a complete, production-ready Next.js 14 website for: "${prompt}"

Requirements:
- Modern, responsive design with Tailwind CSS
- TypeScript
- App Router structure
- Professional styling
- Mobile-first approach

Generate these exact files:

File: package.json
\`\`\`json
{
  "name": "wfseek-generated",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.3.0",
    "postcss": "^8.4.0",
    "autoprefixer": "^10.4.0",
    "lucide-react": "^0.292.0",
    "clsx": "^2.0.0",
    "tailwind-merge": "^2.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "typescript": "^5.3.0"
  }
}
\`\`\`

File: app/layout.tsx
\`\`\`tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '${prompt.split(' ').slice(0, 3).join(' ')}',
  description: 'Generated by Wfseek',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
\`\`\`

File: app/globals.css
\`\`\`css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  html {
    scroll-behavior: smooth;
  }
  
  body {
    @apply bg-gray-50 text-gray-900 antialiased;
  }
}

@layer components {
  .btn-primary {
    @apply bg-blue-600 text-white px-6 py-3 rounded-lg font-medium 
           hover:bg-blue-700 transition-all duration-200 
           hover:shadow-lg hover:-translate-y-0.5;
  }
}
\`\`\`

File: tailwind.config.ts
\`\`\`typescript
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
export default config;
\`\`\`

File: postcss.config.js
\`\`\`javascript
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
\`\`\`

File: tsconfig.json
\`\`\`json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
\`\`\`

File: next.config.js
\`\`\`javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  distDir: 'dist',
  images: { unoptimized: true }
};

module.exports = nextConfig;
\`\`\`

File: app/page.tsx (Create a complete, beautiful landing page based on: "${prompt}")
Include:
- Hero section with headline and CTA
- Features section (3-4 features)
- About section
- Contact or CTA section
- Footer
- Responsive navigation
- Modern gradients and animations
- Use Lucide icons where appropriate

Make it visually stunning with:
- Gradient backgrounds
- Smooth animations
- Professional typography
- Good spacing and layout
- Mobile responsive

Return the complete file contents for all files. Use proper TypeScript and Tailwind CSS.
`;

    const result = await model.generateContent(generationPrompt);
    const generatedText = result.response.text();

    // 3. Parse files
    console.log('📁 Wfseek: Parsing files...');
    const files = parseCodeBlocks(generatedText);
    
    if (files.length === 0) {
      throw new Error('No files were generated. Please try again.');
    }

    // 4. Write files to temp directory
    console.log('💾 Wfseek: Writing files...');
    await fs.ensureDir(projectPath);
    
    for (const file of files) {
      const fullPath = path.join(projectPath, file.path);
      await fs.ensureDir(path.dirname(fullPath));
      await fs.writeFile(fullPath, file.content);
      console.log(`  ✓ ${file.path}`);
    }

    // 5. Install dependencies
    console.log('📦 Wfseek: Installing dependencies...');
    try {
      execSync('npm install', { 
        cwd: projectPath, 
        stdio: 'pipe',
        timeout: 120000,
        env: { ...process.env, NODE_ENV: 'production' }
      });
    } catch (installError) {
      console.log('⚠️  Install warning:', installError.message);
      // Continue anyway
    }

    // 6. Build project
    console.log('🔨 Wfseek: Building project...');
    try {
      execSync('npm run build', { 
        cwd: projectPath, 
        stdio: 'pipe',
        timeout: 180000,
        env: { ...process.env, NODE_ENV: 'production' }
      });
    } catch (buildError) {
      console.error('Build error:', buildError);
      throw new Error('Build failed: ' + buildError.message);
    }

    // 7. Create zip for download
    console.log('📦 Wfseek: Creating zip...');
    const zipPath = path.join('/tmp', `${projectId}.zip`);
    await createZip(projectPath, zipPath);
    const zipBuffer = await fs.readFile(zipPath);
    const zipBase64 = zipBuffer.toString('base64');

    // 8. Try to deploy to Vercel if token exists
    let deployUrl = null;
    
    if (deployToken) {
      console.log('🚀 Wfseek: Deploying to Vercel...');
      try {
        // Create vercel.json
        await fs.writeJson(path.join(projectPath, 'vercel.json'), {
          version: 2,
          builds: [{ src: 'package.json', use: '@vercel/next' }]
        });

        // Deploy using Vercel CLI
        const deployOutput = execSync(
          `npx vercel --token ${deployToken} --yes --prod`, 
          { 
            cwd: projectPath,
            encoding: 'utf-8',
            timeout: 120000,
            env: { ...process.env, VERCEL_TOKEN: deployToken }
          }
        );

        const urlMatch = deployOutput.match(/https:\/\/[a-zA-Z0-9-]+\.vercel\.app/);
        if (urlMatch) {
          deployUrl = urlMatch[0];
          console.log('✅ Wfseek: Deployed to', deployUrl);
        }
      } catch (deployError) {
        console.log('⚠️  Deploy skipped:', deployError.message);
      }
    }

    // Cleanup
    try {
      await fs.remove(projectPath);
      await fs.remove(zipPath);
    } catch (e) {
      // Ignore cleanup errors
    }

    // Return success
    return res.status(200).json({
      success: true,
      message: deployUrl ? 'Website deployed successfully!' : 'Website built successfully!',
      url: deployUrl,
      files: files.map(f => f.path),
      downloadUrl: `data:application/zip;base64,${zipBase64}`,
      projectId
    });

  } catch (error) {
    console.error('❌ Wfseek Error:', error);
    
    // Cleanup on error
    try { 
      await fs.remove(projectPath); 
    } catch(e) {}

    return res.status(500).json({ 
      success: false,
      error: error.message || 'Build failed',
      details: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
}

// Helper: Parse code blocks from AI response
function parseCodeBlocks(text) {
  const files = [];
  const regex = /File:\s*([^\n]+)\n```(?:\w+)?\n([\s\S]*?)```/g;
  let match;
  
  while ((match = regex.exec(text)) !== null) {
    files.push({
      path: match[1].trim(),
      content: match[2].trim()
    });
  }
  
  // Fallback: try to find any markdown code blocks
  if (files.length === 0) {
    const fallbackRegex = /```(?:\w+)?\n([\s\S]*?)```/g;
    let count = 0;
    while ((match = fallbackRegex.exec(text)) !== null) {
      files.push({
        path: `file-${count++}.txt`,
        content: match[1].trim()
      });
    }
  }
  
  return files;
}

// Helper: Create zip file
function createZip(sourceDir, outPath) {
  return new Promise((resolve, reject) => {
    const output = createWriteStream(outPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => resolve());
    archive.on('error', (err) => reject(err));

    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
    }
      
